version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "UTC"
    commit-message:
      prefix: "ci"
      include: "scope"
      prefix-development: "ci"
    open-pull-requests-limit: 5
    reviewers:
      - "maintainers"
    assignees:
      - "maintainers"
    labels:
      - "dependencies"
      - "automated"
    ignore:
      - dependency-name: "actions/checkout"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "UTC"
    commit-message:
      prefix: "build"
      include: "scope"
      prefix-development: "build"
    open-pull-requests-limit: 3
    reviewers:
      - "maintainers"
    assignees:
      - "maintainers"
    labels:
      - "dependencies"
      - "docker"
      - "security"
    ignore:
      - dependency-name: "alpine"
        versions: ["edge"]
